// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace PROJEKAT.Migrations
{
    [DbContext(typeof(PlivackiKlubContext))]
    [Migration("20220321064832_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Disciplina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Distanca")
                        .HasColumnType("int");

                    b.Property<string>("Stil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adresa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BrTelefona")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Klubovi");
                });

            modelBuilder.Entity("Models.Plivac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlubID")
                        .HasColumnType("int");

                    b.Property<string>("Kontakt")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("NivoSpreme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("KlubID");

                    b.ToTable("Plivac");
                });

            modelBuilder.Entity("Models.Takmicenje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drzava")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VelicinaBazena")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Takmicenja");
                });

            modelBuilder.Entity("Models.Ucestvuje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DisciplinaID")
                        .HasColumnType("int");

                    b.Property<int>("Plasman")
                        .HasColumnType("int");

                    b.Property<int?>("PlivacID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Rezultat")
                        .HasColumnType("time");

                    b.Property<int?>("TakmicenjeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DisciplinaID");

                    b.HasIndex("PlivacID");

                    b.HasIndex("TakmicenjeID");

                    b.ToTable("Ucestvuje");
                });

            modelBuilder.Entity("Models.Plivac", b =>
                {
                    b.HasOne("Models.Klub", "Klub")
                        .WithMany("ListaPlivaca")
                        .HasForeignKey("KlubID");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Models.Ucestvuje", b =>
                {
                    b.HasOne("Models.Disciplina", "Disciplina")
                        .WithMany("DisciplinaNaTakmicenjima")
                        .HasForeignKey("DisciplinaID");

                    b.HasOne("Models.Plivac", "Plivac")
                        .WithMany("PlivacNaTakmicenjima")
                        .HasForeignKey("PlivacID");

                    b.HasOne("Models.Takmicenje", "Takmicenje")
                        .WithMany("PlivaciUcestvuju")
                        .HasForeignKey("TakmicenjeID");

                    b.Navigation("Disciplina");

                    b.Navigation("Plivac");

                    b.Navigation("Takmicenje");
                });

            modelBuilder.Entity("Models.Disciplina", b =>
                {
                    b.Navigation("DisciplinaNaTakmicenjima");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Navigation("ListaPlivaca");
                });

            modelBuilder.Entity("Models.Plivac", b =>
                {
                    b.Navigation("PlivacNaTakmicenjima");
                });

            modelBuilder.Entity("Models.Takmicenje", b =>
                {
                    b.Navigation("PlivaciUcestvuju");
                });
#pragma warning restore 612, 618
        }
    }
}
